### ISSUE TITLE
MRCUE suffers from a error

### ISSUE THREAD

**Issue by harryyiheyang** [QingCheng0218/MR.CUE#1]
I hope this message finds you well. I am currently working with MR.CUE and have come across a specific issue that I'm hoping you can assist with.

While I have no issues using the MRCUEIndep function, I encounter an error when transitioning to the MRCUE function, especially when the inputs are labeled as F4Xxxx. The error message I receive is "Not a Matrix". I've double-checked and can confirm that all my inputs are matrices, and they are consistent with the ones I use in MRCUEIndep.

Could you provide some insights or guidance on this matter?

Thank you for your assistance.

**Comment by QingCheng0218** [comment]
Dear Harry,

Thank you for your interest in our paper.
When utilizing the *MRCUE *function in real data analysis, it's important
to note that the inputs labeled in the format F4XXX are, in fact, presented
as a list rather than a matrix. See the following figure.

You can proceed to download the example data and reattempt the application
of this function, as elucidated in the vignette provided at the following
link: https://github.com/QingCheng0218/MR.CUE/blob/main/vignettes/MR-CUE.pdf
.

[image: image.png]

Best,
Qing.

Harry-Yihe-Yang ***@***.***> 于2023年8月10日周四 23:06写道：
